name: eda
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - jupyter
  - seaborn
  - pandas
  - pip=20.3.3
  - pandas-profiling
  - pyarrow
  - protobuf
  - pip:
      - wandb==0.10.31